#  top level
EPOCHS = 'EPOCHS'
MODEL = 'MODEL'

#  top meta
ORDER = 'ORDER'
CURRENT_STEP = 'CURRENT_STEP'
CURRENT_STEP_NAME = 'CURRENT_STEP_NAME'

#  step level
LOADER = 'LOADER'
DATE_ITER = 'DATA_ITER'
USE_GRAD = 'USE_GRAD'
LOSS_FN = 'LOSS_FN'
OPTIMIZER = 'OPTIMIZER'
HOOKS = 'HOOKS'

#  step running
BATCH_DATA = 'BATCH_DATA'

#  hooks
ON_FIT_BEGIN = 'ON_FIT_BEGIN'
ON_FIT_END = 'ON_FIT_END'

ON_EPOCH_BEGIN = 'ON_EPOCH_BEGIN'
ON_EPOCH_END = 'ON_EPOCH_END'

ON_STEP_BEGIN = 'ON_EPOCH_BEGIN'
ON_STEP_END = 'ON_EPOCH_END'

ON_BATCH = 'ON_BATCH'

HOOK_FUNCS = [
    ON_FIT_BEGIN,
    ON_FIT_END,
    ON_EPOCH_BEGIN, 
    ON_EPOCH_END,
    ON_STEP_BEGIN,
    ON_STEP_END,
    ON_BATCH
]